### ISSUE TITLE
сетектори

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/User-Card2#4]
https://github.com/VasylUlianovskyi/User-Card2/blob/4e46601843449c60c8b68a3c15ed200f9be77d85/assets/css/style.css#L125
- використання комбінаторів та псевдокласів доцільно в окремих випадках, де, наприклад, є якась жорстка структура, типу як в таблицях або списках.  (Але добре, що потренували їх😉). Найбільш універсальним є використання класів

**Comment by VasylUlianovskyi** [comment]
++
